In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

## Question 1


In [2]:
np.__version__

'1.19.1'

## Question 2

In [3]:
pd.__version__

'1.1.3'

## Question 3/

In [4]:
df = pd.read_fwf('data.txt')

In [6]:
df.head(5)

Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city  \
0  BMW,1 Series M,2011,premium unleaded (required...                                                                                                                        
1  BMW,1 Series,2011,premium unleaded (required),...                                                                                                                        
2  BMW,1 Series,2011,premium unleaded (required),...                                                                                                                        
3  BMW,1 Series,2011,premium unleaded (required),...                                                                                                                        
4  BMW,1 Series,2011,premium unleaded (required),...                                                                                                                        

  mpg,Popularity,MSRP  
0                 NaN  
1                 NaN  
2                 NaN  
3                 NaN  
4                 NaN

In [7]:
df = pd.read_csv('data.txt', sep=',')

In [8]:
df.head(5)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [13]:
df[df['Make']=='BMW']['MSRP'].mean()

61546.76347305389

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

## Question 4

In [24]:
df[df['Year']>=2015]['Engine HP'].isna().sum()

51

In [21]:
df[df['Year']>=2015].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5995 entries, 32 to 11902
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               5995 non-null   object 
 1   Model              5995 non-null   object 
 2   Year               5995 non-null   int64  
 3   Engine Fuel Type   5995 non-null   object 
 4   Engine HP          5944 non-null   float64
 5   Engine Cylinders   5987 non-null   float64
 6   Transmission Type  5995 non-null   object 
 7   Driven_Wheels      5995 non-null   object 
 8   Number of Doors    5990 non-null   float64
 9   Market Category    4671 non-null   object 
 10  Vehicle Size       5995 non-null   object 
 11  Vehicle Style      5995 non-null   object 
 12  highway MPG        5995 non-null   int64  
 13  city mpg           5995 non-null   int64  
 14  Popularity         5995 non-null   int64  
 15  MSRP               5995 non-null   int64  
dtypes: float64(3), int64(5

In [22]:
5995-5944

51

## Question 5

In [43]:
mean_hp = df['Engine HP'].mean()
mean_hp

249.38607007176023

In [44]:
df_new = df.copy()
#df[df['Year']>=2015]['Engine HP'].fillna(value=mean_hp, inplace = True)
df_new['Engine HP'].fillna(value=mean_hp, inplace = True)

In [45]:
df_new['Engine HP'].mean()

249.38607007176023

In [46]:
df_new['Engine HP'].isna().sum()

0

## Question 6

In [47]:
select_columns = ["Engine HP", "Engine Cylinders", "highway MPG"]

In [50]:
X = df[df['Make']=='Rolls-Royce'][select_columns].drop_duplicates().to_numpy()
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [52]:
np.matmul(X.T, X)

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [54]:
np.linalg.inv(np.matmul(X.T, X))

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [55]:
np.linalg.inv(np.matmul(X.T, X)).sum()

0.032212320677486195

In [57]:
XTX = np.linalg.inv(np.matmul(X.T, X))

## Question 7

In [56]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [58]:
m_1 = np.matmul(XTX, X.T)

In [59]:
w = np.matmul(m_1, y)

In [60]:
w

array([ 0.19989598, 31.02612262, 31.65378877])